language: node_js
node_js:
  - 8
env:
  - FRESH_DEPS=false
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm install --global npm@5.4.2
  - npm --version
install:
  - if [[ ${FRESH_DEPS} == "true" ]]; then npm install --no-shrinkwrap --prefer-online; else npm install --prefer-offline; fi